In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
sales = pd.read_csv("../data/raw/bm_sales.csv")

sales.head()

,date,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct
0,2021-01-01,26,1124,2961.0,1,20.08,20.08,Store,15.0
1,2021-01-01,19,1035,NaN,3,208.57,625.71,Store,15.0
2,2021-01-01,38,1088,NaN,1,17.99,17.99,Website,15.0
3,2021-01-01,3,1164,3694.0,6,196.24,1177.44,Website,0.0
4,2021-01-01,2,1093,1252.0,1,7.98,7.98,Store,0.0

In [16]:
sales.shape

(641843, 9)

In [17]:
sales.columns.tolist()

['date',
 'store_id',
 'sku_id',
 'customer_id',
 'quantity',
 'unit_price',
 'total_value',
 'channel',
 'discount_pct']

In [18]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 641843 entries, 0 to 641842
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   date          641843 non-null  str
 1   store_id      641843 non-null  int64
 2   sku_id        641843 non-null  int64
 3   customer_id   482022 non-null  float64
 4   quantity      641843 non-null  int64
 5   unit_price    641843 non-null  float64
 6   total_value   641843 non-null  float64
 7   channel       641843 non-null  str
 8   discount_pct  641843 non-null  float64
dtypes: float64(4), int64(3), str(2)
memory usage: 44.1 MB

In [19]:
sales.isnull().sum()

date                 0
store_id             0
sku_id               0
customer_id     159821
quantity             0
unit_price           0
total_value          0
channel              0
discount_pct         0
dtype: int64

In [20]:
sales.duplicated().sum()

np.int64(45)

In [21]:
sales.describe()

,store_id,sku_id,customer_id,quantity,unit_price,total_value,discount_pct
count,641843.000000,641843.000000,482022.000000,641843.000000,641843.000000,641843.000000,641843.000000
mean,25.491081,1100.547835,2504.986828,2.613120,44.109242,114.069845,5.411316
std,14.437269,57.684158,1442.340254,1.481563,48.984342,157.206354,8.664765
min,1.000000,1001.000000,1.000000,1.000000,1.700000,1.700000,0.000000
25%,13.000000,1051.000000,1260.000000,1.000000,14.280000,27.320000,0.000000
50%,25.000000,1101.000000,2507.000000,2.000000,24.330000,57.660000,0.000000
75%,38.000000,1150.000000,3752.000000,4.000000,49.570000,129.550000,10.000000
max,50.000000,1200.000000,5000.000000,6.000000,245.380000,1472.280000,35.000000

In [22]:
sales["channel"].value_counts()

channel
Store        274802
Website      174549
MobileApp    111264
Amazon.ae     55171
Noon          26057
Name: count, dtype: int64

In [23]:
duplicates = sales[sales.duplicated(keep=False)]

duplicates.sort_values(
    by=["date", "store_id", "sku_id"]
).head(20)

,date,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct
5463,2021-01-12,28,1061,NaN,2,45.75,91.50,Store,15.0
5783,2021-01-12,28,1061,NaN,2,45.75,91.50,Store,15.0
31125,2021-03-06,10,1037,NaN,1,178.57,178.57,Store,0.0
31306,2021-03-06,10,1037,NaN,1,178.57,178.57,Store,0.0
66354,2021-06-06,10,1145,NaN,1,11.46,11.46,Store,0.0
66573,2021-06-06,10,1145,NaN,1,11.46,11.46,Store,0.0
71206,2021-06-19,13,1024,NaN,2,8.79,17.58,Store,0.0
71332,2021-06-19,13,1024,NaN,2,8.79,17.58,Store,0.0
87236,2021-07-31,27,1069,NaN,5,34.47,172.35,MobileApp,10.0
87384,2021-07-31,27,1069,NaN,5,34.47,172.35,MobileApp,10.0
106460,2021-10-01,33,1045,NaN,1,141.21,141.21,Website,0.0
106520,2021-10-01,33,1045,NaN,1,141.21,141.21,Website,0.0
107158,2021-10-04,2,1159,NaN,3,178.08,534.24,Store,0.0
107188,2021-10-04,2,1159,NaN,3,178.08,534.24,Store,0.0
126410,2021-12-11,46,1146,NaN,1,20.29,20.29,Website,0.0
126550,2021-12-11,46,1146,NaN,1,20.29,20.29,Website,0.0
139877,2022-01-13,35,1133,NaN,3,25.39,76.17,Store,25.0
140138,2022-01-13,35,1133,NaN,3,25.39,76.17,Store,25.0
147693,2022-01-29,25,1107,NaN,3,120.58,361.74,Store,25.0
147735,2022-01-29,25,1107,NaN,3,120.58,361.74,Store,25.0

In [24]:
sales[
    ["quantity", "unit_price", "total_value", "discount_pct"]
].describe()

            quantity     unit_price    total_value   discount_pct
count  641843.000000  641843.000000  641843.000000  641843.000000
mean        2.613120      44.109242     114.069845       5.411316
std         1.481563      48.984342     157.206354       8.664765
min         1.000000       1.700000       1.700000       0.000000
25%         1.000000      14.280000      27.320000       0.000000
50%         2.000000      24.330000      57.660000       0.000000
75%         4.000000      49.570000     129.550000      10.000000
max         6.000000     245.380000    1472.280000      35.000000

In [25]:
sales["calculated_value"] = sales["quantity"] * sales["unit_price"]

sales[
    ["quantity", "unit_price", "total_value", "calculated_value", "discount_pct"]
].head(10)

   quantity  unit_price  total_value  calculated_value  discount_pct
0         1       20.08        20.08             20.08          15.0
1         3      208.57       625.71            625.71          15.0
2         1       17.99        17.99             17.99          15.0
3         6      196.24      1177.44           1177.44           0.0
4         1        7.98         7.98              7.98           0.0
5         1       42.13        42.13             42.13          15.0
6         3       19.93        59.79             59.79          15.0
7         2       37.35        74.70             74.70          15.0
8         3       31.88        95.64             95.64           0.0
9         5      179.73       898.65            898.65           0.0

In [26]:
(sales["total_value"] - sales["calculated_value"]).abs().describe()

count    6.418430e+05
mean     2.421004e-15
std      1.204950e-14
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.273737e-13
dtype: float64

In [27]:
# Remove temporary validation column
sales.drop(columns=["calculated_value"], inplace=True)

# Convert date
sales["date"] = pd.to_datetime(sales["date"])

# Fix customer ID datatype while keeping missing customers
sales["customer_id"] = sales["customer_id"].astype("Int64")

# Remove duplicate rows
sales = sales.drop_duplicates()

# Calculate revenue after discount
sales["net_sales"] = (
    sales["total_value"] * (1 - sales["discount_pct"] / 100)
)

# Create useful date columns
sales["year"] = sales["date"].dt.year
sales["month"] = sales["date"].dt.month
sales["month_name"] = sales["date"].dt.month_name()
sales["day_of_week"] = sales["date"].dt.day_name()

# Check result
print("Rows:", len(sales))
print("Duplicates:", sales.duplicated().sum())
print("\nMissing values:")
print(sales.isnull().sum())

Rows: 641798
Duplicates: 0

Missing values:
date                 0
store_id             0
sku_id               0
customer_id     159777
quantity             0
unit_price           0
total_value          0
channel              0
discount_pct         0
net_sales            0
year                 0
month                0
month_name           0
day_of_week          0
dtype: int64

In [28]:
sales.to_csv(
    "../data/cleaned/bm_sales_cleaned.csv",
    index=False
)

print("Cleaned sales data saved successfully!")

Cleaned sales data saved successfully!